M48
; DRILL file {KiCad 7.0.10} date gio 1 feb 2024, 18:49:42
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-01T18:49:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0902
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X4.8063Y-3.6839
X4.8063Y-4.7457
X5.6862Y-4.215
T2
X3.2Y-2.2
X5.75Y-5.5
M30
